version: '3.8'

services:
  warehouse-app:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
      - warehouse-logs:/var/log/warehouse
      - warehouse-backups:/var/backups/warehouse
    env_file:
      - .env.production
    depends_on:
      - warehouse-db
    networks:
      - warehouse-network

  warehouse-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: warehouse_db
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    volumes:
      - warehouse-db-data:/var/lib/postgresql/data
    networks:
      - warehouse-network

  nginx:
    image: nginx:1.21
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/static:/var/www/static
    depends_on:
      - warehouse-app
    networks:
      - warehouse-network

volumes:
  warehouse-db-data:
  warehouse-logs:
  warehouse-backups:

networks:
  warehouse-network:
    driver: bridge