services:
  webapp:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - ./backups:/app/backups
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - FLASK_SECRET_KEY=your_secure_secret_key_change_this_in_production
      - DATABASE_URL=sqlite:///database.db
      - PLC_OPC_UA_URL=opc.tcp://your.plc.ip.address:4840  # Update to your actual PLC address
      - BACKUP_DIR=backups
      - BACKUP_INTERVAL=86400
    restart: unless-stopped
    command: python run.py # Use Python directly instead of Flask CLI
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s